<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $currencies = array(
            array('code' => 'AED','symbol' => 'د.إ','name' => 'United Arab Emirates dirham'),
            array('code' => 'AFN','symbol' => '؋','name' => 'Afghan afghani'),
            array('code' => 'ALL','symbol' => 'L','name' => 'Albanian lek'),
            array('code' => 'AMD','symbol' => 'դր.','name' => 'Armenian dram'),
            array('code' => 'ANG','symbol' => 'ƒ','name' => 'Netherlands Antillean guilder'),
            array('code' => 'AOA','symbol' => 'Kz','name' => 'Angolan kwanza'),
            array('code' => 'ARS','symbol' => '$','name' => 'Argentine peso'),
            array('code' => 'AUD','symbol' => 'A$','name' => 'Australian dollar'),
            array('code' => 'AWG','symbol' => 'ƒ','name' => 'Aruban florin'),
            array('code' => 'AZN','symbol' => '₼','name' => 'Azerbaijani manat'),
            array('code' => 'BAM','symbol' => 'КМ','name' => 'Bosnia and Herzegovina convertible mark'),
            array('code' => 'BBD','symbol' => '$','name' => 'Barbadian dollar'),
            array('code' => 'BDT','symbol' => '৳','name' => 'Bangladeshi taka'),
            array('code' => 'BGN','symbol' => 'лв','name' => 'Bulgarian lev'),
            array('code' => 'BHD','symbol' => 'ب.د','name' => 'Bahraini dinar'),
            array('code' => 'BIF','symbol' => 'Fr','name' => 'Burundian franc'),
            array('code' => 'BMD','symbol' => '$','name' => 'Bermudian dollar'),
            array('code' => 'BND','symbol' => '$','name' => 'Brunei dollar'),
            array('code' => 'BOB','symbol' => 'Bs.','name' => 'Bolivian boliviano'),
            array('code' => 'BRL','symbol' => 'R$','name' => 'Brazilian real'),
            array('code' => 'BSD','symbol' => '$','name' => 'Bahamian dollar'),
            array('code' => 'BTN','symbol' => 'Nu.','name' => 'Bhutanese ngultrum'),
            array('code' => 'BWP','symbol' => 'P','name' => 'Botswana pula'),
            array('code' => 'BYR','symbol' => 'Br','name' => 'Belarusian ruble'),
            array('code' => 'BZD','symbol' => '$','name' => 'Belize dollar'),
            array('code' => 'CAD','symbol' => '$','name' => 'Canadian dollar'),
            array('code' => 'CDF','symbol' => 'Fr','name' => 'Congolese franc'),
            array('code' => 'CHF','symbol' => 'Fr','name' => 'Swiss franc'),
            array('code' => 'CLP','symbol' => '$','name' => 'Chilean peso'),
            array('code' => 'CNY','symbol' => '元','name' => 'Chinese yuan'),
            array('code' => 'COP','symbol' => '$','name' => 'Colombian peso'),
            array('code' => 'CRC','symbol' => '₡','name' => 'Costa Rican colón'),
            array('code' => 'CUC','symbol' => '$','name' => 'Cuban convertible peso'),
            array('code' => 'CUP','symbol' => '$','name' => 'Cuban peso'),
            array('code' => 'CVE','symbol' => 'Esc','name' => 'Cape Verdean escudo'),
            array('code' => 'CZK','symbol' => 'Kč','name' => 'Czech koruna'),
            array('code' => 'DJF','symbol' => 'Fr','name' => 'Djiboutian franc'),
            array('code' => 'DKK','symbol' => 'kr','name' => 'Danish krone'),
            array('code' => 'DOP','symbol' => '$','name' => 'Dominican peso'),
            array('code' => 'DZD','symbol' => 'د.ج','name' => 'Algerian dinar'),
            array('code' => 'EEK','symbol' => 'KR','name' => 'Estonian kroon'),
            array('code' => 'EGP','symbol' => 'ج.م','name' => 'Egyptian pound'),
            array('code' => 'ERN','symbol' => 'Nfk','name' => 'Eritrean nakfa'),
            array('code' => 'ETB','symbol' => 'ብር','name' => 'Ethiopian birr'),
            array('code' => 'EUR','symbol' => '€','name' => 'Euro'),
            array('code' => 'FJD','symbol' => '$','name' => 'Fijian dollar'),
            array('code' => 'FKP','symbol' => '£','name' => 'Falkland Islands pound'),
            array('code' => 'GBP','symbol' => '£','name' => 'British pound'),
            array('code' => 'GEL','symbol' => 'ლ','name' => 'Georgian lari'),
            array('code' => 'GHS','symbol' => '₵','name' => 'Ghanaian cedi'),
            array('code' => 'GIP','symbol' => '£','name' => 'Gibraltar pound'),
            array('code' => 'GMD','symbol' => 'D','name' => 'Gambian dalasi'),
            array('code' => 'GNF','symbol' => 'Fr','name' => 'Guinean franc'),
            array('code' => 'GTQ','symbol' => 'Q','name' => 'Guatemalan quetzal'),
            array('code' => 'GYD','symbol' => '$','name' => 'Guyanese dollar'),
            array('code' => 'HKD','symbol' => '$','name' => 'Hong Kong dollar'),
            array('code' => 'HNL','symbol' => 'L','name' => 'Honduran lempira'),
            array('code' => 'HRK','symbol' => 'kn','name' => 'Croatian kuna'),
            array('code' => 'HTG','symbol' => 'G','name' => 'Haitian gourde'),
            array('code' => 'HUF','symbol' => 'Ft','name' => 'Hungarian forint'),
            array('code' => 'IDR','symbol' => 'Rp','name' => 'Indonesian rupiah'),
            array('code' => 'ILS','symbol' => '₪','name' => 'Israeli new sheqel'),
            array('code' => 'INR','symbol' => '₹','name' => 'Indian rupee'),
            array('code' => 'IQD','symbol' => 'ع.د','name' => 'Iraqi dinar'),
            array('code' => 'IRR','symbol' => '﷼','name' => 'Iranian rial'),
            array('code' => 'ISK','symbol' => 'kr','name' => 'Icelandic króna'),
            array('code' => 'JMD','symbol' => '$','name' => 'Jamaican dollar'),
            array('code' => 'JOD','symbol' => 'د.ا','name' => 'Jordanian dinar'),
            array('code' => 'JPY','symbol' => '¥','name' => 'Japanese yen'),
            array('code' => 'KES','symbol' => 'Sh','name' => 'Kenyan shilling'),
            array('code' => 'KGS','symbol' => 'Лв','name' => 'Kyrgyzstani som'),
            array('code' => 'KHR','symbol' => '៛','name' => 'Cambodian riel'),
            array('code' => 'KMF','symbol' => 'Fr','name' => 'Comorian franc'),
            array('code' => 'KPW','symbol' => '₩','name' => 'North Korean won'),
            array('code' => 'KRW','symbol' => '₩','name' => 'South Korean won'),
            array('code' => 'KWD','symbol' => 'د.ك','name' => 'Kuwaiti dinar'),
            array('code' => 'KYD','symbol' => '$','name' => 'Cayman Islands dollar'),
            array('code' => 'KZT','symbol' => '〒','name' => 'Kazakhstani tenge'),
            array('code' => 'LAK','symbol' => '₭','name' => 'Lao kip'),
            array('code' => 'LBP','symbol' => 'ل.ل','name' => 'Lebanese pound'),
            array('code' => 'LKR','symbol' => 'Rs','name' => 'Sri Lankan rupee'),
            array('code' => 'LRD','symbol' => '$','name' => 'Liberian dollar'),
            array('code' => 'LSL','symbol' => 'L','name' => 'Lesotho loti'),
            array('code' => 'LTL','symbol' => 'Lt','name' => 'Lithuanian litas'),
            array('code' => 'LVL','symbol' => 'Ls','name' => 'Latvian lats'),
            array('code' => 'LYD','symbol' => 'ل.د','name' => 'Libyan dinar'),
            array('code' => 'MAD','symbol' => 'د.م.','name' => 'Moroccan dirham'),
            array('code' => 'MDL','symbol' => 'L','name' => 'Moldovan leu'),
            array('code' => 'MGA','symbol' => 'Ar','name' => 'Malagasy ariary'),
            array('code' => 'MKD','symbol' => 'ден','name' => 'Macedonian denar'),
            array('code' => 'MMK','symbol' => 'K','name' => 'Myanma kyat'),
            array('code' => 'MNT','symbol' => '₮','name' => 'Mongolian tögrög'),
            array('code' => 'MOP','symbol' => 'P','name' => 'Macanese pataca'),
            array('code' => 'MRO','symbol' => 'UM','name' => 'Mauritanian ouguiya'),
            array('code' => 'MUR','symbol' => '₨','name' => 'Mauritian rupee'),
            array('code' => 'MVR','symbol' => 'ރ.','name' => 'Maldivian rufiyaa'),
            array('code' => 'MWK','symbol' => 'MK','name' => 'Malawian kwacha'),
            array('code' => 'MXN','symbol' => '$','name' => 'Mexican peso'),
            array('code' => 'MYR','symbol' => 'RM','name' => 'Malaysian ringgit'),
            array('code' => 'MZN','symbol' => 'MTn','name' => 'Mozambican metical'),
            array('code' => 'NAD','symbol' => '$','name' => 'Namibian dollar'),
            array('code' => 'NGN','symbol' => '₦','name' => 'Nigerian naira'),
            array('code' => 'NIO','symbol' => 'C$','name' => 'Nicaraguan córdoba'),
            array('code' => 'NOK','symbol' => 'kr','name' => 'Norwegian krone'),
            array('code' => 'NPR','symbol' => '₨','name' => 'Nepalese rupee'),
            array('code' => 'NZD','symbol' => '$','name' => 'New Zealand dollar'),
            array('code' => 'OMR','symbol' => 'ر.ع.','name' => 'Omani rial'),
            array('code' => 'PAB','symbol' => 'B/.','name' => 'Panamanian balboa'),
            array('code' => 'PEN','symbol' => 'S/.','name' => 'Peruvian nuevo sol'),
            array('code' => 'PGK','symbol' => 'K','name' => 'Papua New Guinean kina'),
            array('code' => 'PHP','symbol' => '₱','name' => 'Philippine peso'),
            array('code' => 'PKR','symbol' => '₨','name' => 'Pakistani rupee'),
            array('code' => 'PLN','symbol' => 'zł','name' => 'Polish złoty'),
            array('code' => 'PYG','symbol' => '₲','name' => 'Paraguayan guaraní'),
            array('code' => 'QAR','symbol' => 'ر.ق','name' => 'Qatari riyal'),
            array('code' => 'RON','symbol' => 'L','name' => 'Romanian leu'),
            array('code' => 'RSD','symbol' => 'дин.','name' => 'Serbian dinar'),
            array('code' => 'RUB','symbol' => 'руб.','name' => 'Russian ruble'),
            array('code' => 'RWF','symbol' => 'Fr','name' => 'Rwandan franc'),
            array('code' => 'SAR','symbol' => 'ر.س','name' => 'Saudi riyal'),
            array('code' => 'SBD','symbol' => '$','name' => 'Solomon Islands dollar'),
            array('code' => 'SCR','symbol' => '₨','name' => 'Seychellois rupee'),
            array('code' => 'SDG','symbol' => '£','name' => 'Sudanese pound'),
            array('code' => 'SEK','symbol' => 'kr','name' => 'Swedish krona'),
            array('code' => 'SGD','symbol' => '$','name' => 'Singapore dollar'),
            array('code' => 'SHP','symbol' => '£','name' => 'Saint Helena pound'),
            array('code' => 'SLL','symbol' => 'Le','name' => 'Sierra Leonean leone'),
            array('code' => 'SOS','symbol' => 'Sh','name' => 'Somali shilling'),
            array('code' => 'SRD','symbol' => '$','name' => 'Surinamese dollar'),
            array('code' => 'STD','symbol' => 'Db','name' => 'São Tomé and Príncipe dobra'),
            array('code' => 'SVC','symbol' => '₡','name' => 'Salvadoran colón'),
            array('code' => 'SYP','symbol' => 'ل.س','name' => 'Syrian pound'),
            array('code' => 'SZL','symbol' => 'L','name' => 'Swazi lilangeni'),
            array('code' => 'THB','symbol' => '฿','name' => 'Thai baht'),
            array('code' => 'TJS','symbol' => 'ЅМ','name' => 'Tajikistani somoni'),
            array('code' => 'TMM','symbol' => 'm','name' => 'Turkmenistani manat'),
            array('code' => 'TND','symbol' => 'د.ت','name' => 'Tunisian dinar'),
            array('code' => 'TOP','symbol' => 'T$','name' => 'Tongan paʻanga'),
            array('code' => 'TRY','symbol' => '₺','name' => 'Turkish lira'),
            array('code' => 'TTD','symbol' => '$','name' => 'Trinidad and Tobago dollar'),
            array('code' => 'TWD','symbol' => '$','name' => 'New Taiwan dollar'),
            array('code' => 'TZS','symbol' => 'Sh','name' => 'Tanzanian shilling'),
            array('code' => 'UAH','symbol' => '₴','name' => 'Ukrainian hryvnia'),
            array('code' => 'UGX','symbol' => 'Sh','name' => 'Ugandan shilling'),
            array('code' => 'USD','symbol' => '$','name' => 'United States dollar'),
            array('code' => 'UYU','symbol' => '$','name' => 'Uruguayan peso'),
            array('code' => 'UZS','symbol' => 'лв','name' => 'Uzbekistani som'),
            array('code' => 'VEF','symbol' => 'Bs F','name' => 'Venezuelan bolívar'),
            array('code' => 'VND','symbol' => '₫','name' => 'Vietnamese đồng'),
            array('code' => 'VUV','symbol' => 'Vt','name' => 'Vanuatu vatu'),
            array('code' => 'WST','symbol' => 'T','name' => 'Samoan tala'),
            array('code' => 'XAF','symbol' => 'Fr','name' => 'Central African CFA franc'),
            array('code' => 'XCD','symbol' => '$','name' => 'East Caribbean dollar'),
            array('code' => 'XOF','symbol' => 'Fr','name' => 'West African CFA franc'),
            array('code' => 'XPF','symbol' => 'Fr','name' => 'CFP franc'),
            array('code' => 'YER','symbol' => '﷼','name' => 'Yemeni rial'),
            array('code' => 'ZAR','symbol' => 'R','name' => 'South African rand'),
            array('code' => 'ZMK','symbol' => 'ZK','name' => 'Zambian kwacha'),
            array('code' => 'ZWL','symbol' => '$','name' => 'Zimbabwean dollar')
        );

        Currency::insert($currencies);
    }
}

